// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkfrlfvwcvvjneivnjts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rZnJsZnZ3Y3Z2am5laXZuanRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTI1NzQsImV4cCI6MjA2NTU4ODU3NH0.85ILqvRRNjjU4gDaukGN-CaAZkBISk1PE7JMTC_nH0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});